version: '3.8'
services: 
  server:
    container_name: server-container
    restart: always
    build: ./server
    ports: 
      - "5000:5000"
  client:
    container_name: client-container
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - server